- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
Jenkins became requiring JDK1.7.
see [JENKINS-28120] https://github.com/jenkinsci/jenkins/commit/c00935f0b212272c7b00dc446bdbab20a13bb787
> update JDK version.

- .gitignore
- pom.xml
- src/main/java/hudson/plugins/sshslaves/PluginImpl.java
- src/main/java/hudson/plugins/sshslaves/SSHConnector.java
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/resources/hudson/plugins/sshslaves/SSHConnector/config.jelly
- src/main/resources/hudson/plugins/sshslaves/SSHLauncher/config.jelly
Included in this PR:
PCT runs successfully after the upgrade. 
@reviewbybees esp. @stephenc
> [JENKINS-33720] Upgrade to plugin pom 2.4 and bump baseline

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
When the port is not specified, following warning is printed.
[whitespace aware diff](https://github.com/jenkinsci/ssh-slaves-plugin/pull/30/files?w=1)
```
master57956|WARNING: Error while serving http://127.0.0.1:57956/descriptorByName/hudson.plugins.sshslaves.SSHLauncher/fillCredentialsIdItems
master57956|java.lang.reflect.InvocationTargetException
master57956|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
master57956|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
master57956|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
master57956|	at java.lang.reflect.Method.invoke(Method.java:606)
master57956|	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
master57956|	at …
```
> Hide empty port warninig

- pom.xml
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
This is needed to diagnose slave connection initialization issues. Currently, SSH connection initialization is done in a  `Callable` running inside an anonymous and dedicated `ExecutorService`. If something goes wrong and connection timeout is set to 0, connection thread can get stuck and never killed. Without this, we can't find which slave is involved.
Bumping core dependency was required to use `NamingThreadFactory`.
@reviewbybees
> Meaningful thread name for callable establishing SSH connection

- pom.xml
- src/main/resources/index.jelly
[JENKINS-40001](https://issues.jenkins-ci.org/browse/JENKINS-40001)
@reviewbybees, specially @stephenc @olamy @kohsuke
> [JENKINS-40001] Add plugin description to POM.

- pom.xml
- src/main/resources/index.jelly
[JENKINS-42022](https://issues.jenkins-ci.org/browse/JENKINS-42022)
Adapt descriptions in POM and index.jelly files after  [PR #33](https://github.com/jenkinsci/ssh-slaves-plugin/pull/33)
@reviewbybees @stephenc @olamy
> [JENKINS-42022] Remove 'unix machines' from plugin's description.

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
As jdk7 reached end of life, i would recommend to bump the version to a rather recent one.
We might discuss further, if we expose JDKVERSION via "Manage Jenkins".
Like "latest", "please type jdkversion here/choose from these jdks" and a "stable version".
The latter one would behave like a final JDKVERSION.
> [JENKINS-43481] Bump JDKVERSION to jdk8-u121

- pom.xml
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/java/hudson/plugins/sshslaves/verifiers/JenkinsTrilead9VersionSupport.java
- src/main/java/hudson/plugins/sshslaves/verifiers/KeyParseException.java
- src/main/java/hudson/plugins/sshslaves/verifiers/KnownHostsFileKeyVerificationStrategy.java
- src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
- src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyTrustedKeyVerificationStrategy.java
- src/main/java/hudson/plugins/sshslaves/verifiers/SshHostKeyVerificationStrategy.java
- src/main/java/hudson/plugins/sshslaves/verifiers/TrileadVersionSupportManager.java
- src/test/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategyTest.java
- src/test/java/hudson/plugins/sshslaves/verifiers/TrileadVersionSupportManagerTest.java
The remaining fix for JENKINS-42959: adds support for additional host key algorithms where Jenkins contains a newer version of Trilead, and specify the preferred host key algorithm for connecting in-case Jenkins has an old key format saved as the known key.
> [FIXED JENKINS-42959] Specify preferred host keys during connect

- pom.xml
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
[JENKINS-44830](https://issues.jenkins-ci.org/browse/JENKINS-44830)
Amends #54. Reproduces reported NPE.
@reviewbybees
> [JENKINS-44830] NPE after upgrading caused by fix of JENKINS-42959

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
- src/main/java/hudson/plugins/sshslaves/verifiers/SshHostKeyVerificationStrategy.java
[JENKINS-44832](https://issues.jenkins-ci.org/browse/JENKINS-44832)
Amends #54. Not known how to reproduce, so no regression test.
@reviewbybees
> [JENKINS-44832] IAE due to empty or null list of preferred key algorithms

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherWithJDKInstallerTest.java
It works-around the issue with authentication for old JDK versions on the Oracle website.
Have not tested it locally yet. Tests also randomly fail on my machine due to https://github.com/jenkinsci/trilead-ssh2/pull/25.
@reviewbybees @dwnusbaum @jglick
> [JENKINS-47448] - Update the default Java version to 8u144

- src/main/java/hudson/plugins/sshslaves/verifiers/TrileadVersionSupportManager.java
- src/test/java/hudson/plugins/sshslaves/verifiers/TrileadVersionSupportManagerTest.java
Issue link: [https://issues.jenkins-ci.org/browse/JENKINS-44893](https://issues.jenkins-ci.org/browse/JENKINS-44893)
Since the JenkinsTrilead9VersionSupport is within the same classpath as TrileadVersionSupportManager, we can safely instantiate it without worrying class loading issues.
> [JENKINS-44893] Fix Trilead support class instantiation

- Jenkinsfile
- pom.xml
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
- src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java
See [JENKINS-48260](https://issues.jenkins-ci.org/browse/JENKINS-48260)
- Upgrade to `parent-pom:3.0` and update dependencies
- Upgrading baseline to `jenkins.version:2.7` to prevent `IndexOutOfBoundsException` when the ExtensionList is recovered.
- `TrustHostKeyActionTest` updated with new dependency `sshd-core:1.6.0`
- `SSHLauncherTest` updated to check if Java 7 is supported depending on `jenkins.version`
@reviewbybees spec. @stephenc 
@olamy 
@mc1arke
> [JENKINS-48260] Upgrade parent POM and fix PCT

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
It extends my JENKINS-19465 fix in #75 and makes the hack even more hackish.
Ideally Jenkins Core needs to be updated to somehow prevent /queue such duplicated calls in the Executor service. Should be done on a ComputerListener level or so. I will create tickets for that later
@reviewbybees @jglick
> [JENKINS-48613] - Hotfix: Prevent piling up of tearDownConnection() calls if they take long

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
https://issues.jenkins-ci.org/browse/JENKINS-48616
It does not make much difference without [JENKINS-48617](https://issues.jenkins-ci.org/browse/JENKINS-48617) and [JENKINS-48618](https://issues.jenkins-ci.org/browse/JENKINS-48618), but OTOH it is a low-hanging fruit.
@reviewbybees @jglick
> [JENKINS-48616] - Pass launch timeout as Connection and KEx timeout to TrileadSSH

- pom.xml
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
SSHLauncher do receive `credentialsId` but then retrieve matching `Credentials` instance, then stores `credentials.getI()`. Proposed change make it just simpler by storing ID
initial reason doing so :
Running Configuration-as-Code we inject credentialsId during init, while the credentials store might not be setup yet so it can resolve it to an actual credentials instance.
Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>
> don’t lookup systemCredentials to eventually store credentialsId which was initial constructor parameter

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
It will now return:
on jenkins >= JAVA8_MINIMAL_SINCE (=2.54 see JavaProvider.java; Version used defined in jenkins.version of POM.xml)
java.io.IOException: Could not find any known supported java version (a minimum level of 8 is required) in [java, /usr/bin/java, /usr/java/default/bin/java, /usr/java/latest/bin/java, /usr/local/bin/java, /usr/local/java/bin/java, /home/test/slave/jdk/bin/java], and we also failed to install JDK as a fallback
on jenkins < JAVA8_MINIMAL_SINCE (=2.54 see JavaProvider; Version used defined in jenkins.version of POM.xml)
java.io.IOException: Could not find any known supported java version (a minimum level of 7 is required) in [java, /usr/bin/java, /usr/java/default/bin/java, /usr/java/latest/bin/java, /usr/local/bin/java, /usr/local/java/bin/java, …
> [FIXED JENKINS-49607] - Report required java version when none found

- pom.xml
See [JENKINS-49670](https://issues.jenkins-ci.org/browse/JENKINS-49670)
Upgrade docker-fixtures dependency to fix the error when `SSHLauncherTest#upgrade` is executed.
@reviewbybees @olamy @stephenc @oleg-nenashev
> [JENKINS-49670] SSHLauncherTest#upgrade is failing

- src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
- src/main/resources/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor/message.jelly
[JENKINS-43786](https://issues.jenkins-ci.org/browse/JENKINS-43786)
Downstream of https://github.com/jenkinsci/jenkins/pull/2857
@jenkinsci/code-reviewers
> [JENKINS-43786] Adapted the administrative monitor to the new UI definition

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/resources/hudson/plugins/sshslaves/SSHConnector/config.jelly
- src/main/resources/hudson/plugins/sshslaves/SSHConnector/help-workDir.html
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
[JENKINS-44108](https://issues.jenkins-ci.org/browse/JENKINS-44108)
[JENKINS-44111](https://issues.jenkins-ci.org/browse/JENKINS-44111)
* Add support to Remoting Work Directory
* Test for configuration
* Remove some unused imports and some warnings in SSHLauncherTests
> [JENKINS-44108][JENKINS-44111] Remoting Work Directory Support 

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
Use echo > null instead of true command in `verifyNoHeaderJunk()`
Using echo instead of true allows to start windows slaves without cygwin.
This is related to ticket: JENKINS-37152
> JENKINS-37152 Replace 'true' with 'echo'

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
[JENKINS-53254](https://issues.jenkins-ci.org/browse/JENKINS-53254)
It was removed in commit 118423c3de0fd3f5b65183a3f2d62cb2e15a79ca, but
it is still used by at least one plugin.
Mark as deprecated to discourage further use.
> [FIXED JENKINS-53254] Restore getJavaPath() method.

- pom.xml
Now thins are more explicit and also how http://www.mojohaus.org/tidy-maven-plugin/ would format the first lines in the pom.xml.
> Update pom.xml - XML declaration & schema location

- src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
- src/main/resources/hudson/plugins/sshslaves/Messages.properties
See [JENKINS-54269](https://issues.jenkins-ci.org/browse/JENKINS-54269)
The display name for the MissingVerificationStrategyAdministrativeMonitor is missing. This PR adds its display name.
@reviewbybees 
@kuisathaverat as maintainer
> [JENKINS-54269] Missing display name for administrative monitor

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
Enables `0`  for the *number of retries* and *retry wait time* (JENKINS-54934).
> [JENKINS-54934] Number of retries and retry wait time of 0

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
- src/test/resources/readInputStreamIntoByteArrayTestFile.txt
When an ssh agent is launched it will compare the MD5 hash of the remoting jar in Jenkins home with the hash of the remoting.jar in the remote root directory of the agent.
* If the file does not exist or is different, it is copied from the Jenkins master.
* If the file is the same, it is ignored.
This change allows multiple agent nodes to share the same root directory (and workspace) without getting concurrency conflicts that happened when the remoting jar got overwritten with every agent launch.
See https://issues.jenkins-ci.org/browse/JENKINS-5149 and similar.
see the related issue [JENKINS-56147](https://issues.jenkins-ci.org/browse/JENKINS-56147)
> [FIX JENKINS-56147] Overwrite remoting.jar only when necessary.

- CHANGELOG.md
- Jenkinsfile
- pom.xml
- src/main/java/hudson/plugins/sshslaves/SSHConnector.java
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/java/hudson/plugins/sshslaves/verifiers/HostKeyHelper.java
- src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
- src/main/java/hudson/plugins/sshslaves/verifiers/SshHostKeyVerificationStrategy.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
- src/test/java/hudson/plugins/sshslaves/verifiers/VerificationStrategyConfigurationTest.java
[JENKINS-55353](https://issues.jenkins-ci.org/browse/JENKINS-55353)
After tested the plugin to compile against different Jenkins core versions, I have detected some changes that I have to make to test it.
* Update Jenkins file to compile an test on Jenkins core 2.150.1, 2.164.1, and 2.168 (2 LTS and last weekly)
* Compile and test weekly with JDK 11
* Upgrade Jenkins core to 2.150.1, I will support 2 LTS versions
* Remove JDKInstaler references, is not used in ssh-slaves and it is no longer in Jenkins core, it is in tool-jdk plugin
* Remove deprecated constructors, all these constructors were marked with a warning in logs 6 months ago.
* Remove unused code
* Remove old fields related to deprecated constructors
* Fix tests after changes
* Remove deprecated package dependency javax.xml.bind …
> [JENKINS-55353] Upgrade Jenkins core to 2.150.1

- src/main/java/hudson/plugins/sshslaves/SSHConnector.java
This utilizes the change introduced by #90. Essentially it allows the new setting can be set for instances of SSHConnector. Effectively, we can change and persist this setting in the ec2-fleet-plugin when SSHConnector is used as a launcher.
[JENKINS-57018](https://issues.jenkins-ci.org/browse/JENKINS-57018)
> [JENKINS-57018] Allow to enable/disable TCP_NODELAY in SSHConnector

- src/main/java/hudson/plugins/sshslaves/SSHConnector.java
This sets the working directory in instances of SSHConnector and passes the value to the SSHLauncher instances.
[JENKINS-57019](https://issues.jenkins-ci.org/browse/JENKINS-57019)
> [JENKINS-57019] Allow to set working directory in SSHConnector

- pom.xml
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherCasCRoundTripTest.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherCasCSupport.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherCasCSupportTest.java
- src/test/resources/hudson/plugins/sshslaves/SSHCasCConfig.yml
- src/test/resources/hudson/plugins/sshslaves/SSHCasCConfigLegacy.yml
[JENKINS-57797](https://issues.jenkins-ci.org/browse/JENKINS-57797)
This PR aims to validate the support of configuration-as-code for this plugin.
By default, the configuration is supported, but under the section `sSHLauncher`, this is why I added the `@Symbol` on the `SSHLauncher` descriptor.
> [JENKINS-57797] Support Configuration-as-Code

- pom.xml
- src/test/java/hudson/plugins/sshslaves/SSHLauncherCasCRoundTripTest.java
Update the casc version and the name of the class because the parent class was renamed at the last minute.
CC: @alecharp @kuisathaverat
> [JENKINS-57797] Update Casc version and rename classes to fit the parent

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
see [JENKINS-58340](https://issues.jenkins-ci.org/browse/JENKINS-58340)
> [JENKINS-58340] docker-plugin-1.1.6 docker cloud does not work with >=ssh-slaves-plugin-1.30.0

- src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
- src/main/resources/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor/message.jelly
I was perusing the source tree while debugging an unrelated issue and came across this TODO. The TODO was added in #70. At the time, this plugin's baseline was 1.625, so #70 needed a way to support Jenkins core versions both with [JENKINS-43786](https://issues.jenkins-ci.org/browse/JENKINS-43786) (i.e., 2.103 and later) and without it. This plugin's baseline is now 2.150.1, which does contain [JENKINS-43786](https://issues.jenkins-ci.org/browse/JENKINS-43786). So now the logic to support older baselines is dead code that can be removed.
To test this change, I ran `mvn clean package` locally. It passed. Please let me know if there is any additional testing I should do.
> Remove dead code for no-longer-supported baselines

- doc/TROUBLESHOOTING.md
see [JENKINS-57126](https://issues.jenkins-ci.org/browse/JENKINS-57126)
add instructions to use workdir in a no C drive
> docs: add instructions to use workdir in a no C drive

- src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
- src/main/resources/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy/config.jelly
see [JENKINS-56187](https://issues.jenkins-ci.org/browse/JENKINS-56187)
* catch IllegalArgumentException to avoid show the exception in the UI
* sent the public key using POST method to prevent too long GET request errors
> [JENKINS-56187] manually provided key verification strategy crashes

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/resources/hudson/plugins/sshslaves/Messages.properties
see [JENKINS-54897](https://issues.jenkins-ci.org/browse/JENKINS-54897)
it is possible to start several launch process at the same time, this end in a mess that many of times do not start the agent. This will stop to try to launch an Agent if it is connected or in the process.
> [JENKINS-54897] block connection when a connection exists

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/resources/hudson/plugins/sshslaves/SSHConnector/help-workDir.html
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
see [JENKINS-44111](https://issues.jenkins-ci.org/browse/JENKINS-44111)
it adds also the `-jar-cache` parameter to move the jar cache to the folder WORKDIR/remoting/jarCache
> [JENKINS-44111] add also jar cache dir parameter

- pom.xml
- src/test/java/hudson/plugins/sshslaves/SSHLauncherCasCRoundTripTest.java
See [JENKINS-59251](https://issues.jenkins-ci.org/browse/JENKINS-59251)
Current version of JCasC is 1.29 and it includes important security fixes introduced in 1.25 and 1.27 (See https://github.com/jenkinsci/configuration-as-code-plugin/releases).
v1.25 also introduces some breaking changes, so to be sure the plugin remains compatible with JCasC, it's worth to update the dependency.
@kuisathaverat 
@oleg-nenashev @MRamonLeon @alecharp @varyvol @rsandell
> [JENKINS-59251] Update JCasC to version with security fixes

- Jenkinsfile
- pom.xml
See [JENKINS-59728](https://issues.jenkins-ci.org/browse/JENKINS-59728).
because Jenkins core 2.190.1 no longer has trilead-ssh2, I've to bump the core to 1.90.1 and include trilead-api-plugin as a dependency. I will maintain 1.30.x versions for previous cores for awhile.
> [JENKINS-59728] Bump Jenkins core to 2.190.1

- src/main/java/hudson/plugins/sshslaves/RemoteLauncher.java
Backports the following commits to 1.30.x:
- Use ChannelBuilder instead of deprecated Channel constructor  (#152)
> [1.30.x] Use ChannelBuilder instead of deprecated Channel constructor (#152)

- Jenkinsfile
- pom.xml
Backports the following commits to ssh-slaves-2.0:
- [JENKINS-59728] Bump Jenkins core to 2.190.1  (#153)
> [ssh-slaves-2.0] [JENKINS-59728] Bump Jenkins core to 2.190.1 (#153)

- src/main/resources/hudson/plugins/sshslaves/SSHConnector/config_zh_TW.properties
- src/main/resources/hudson/plugins/sshslaves/SSHLauncher/help.properties
- src/main/resources/hudson/plugins/sshslaves/SSHLauncher/help_de.properties
- src/main/resources/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor/message.jelly
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
- src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java
Backports the following commits to ssh-slaves-2.0:
- [JENKINS-42840] Slave to agent renaming (leftovers)  (#151)
> [ssh-slaves-2.0] [JENKINS-42840] Slave to agent renaming (leftovers) (#151)

- src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
Backports the following commits to ssh-slaves-2.0:
- Replace usage of deprecated remoting Base64 class  (#150)
> [ssh-slaves-2.0] Replace usage of deprecated remoting Base64 class (#150)

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
See [JENKINS-53720](https://issues.jenkins-ci.org/browse/JENKINS-53720).
> [JENKINS-53720] JDK11 Build Flow: FindBugs fails with RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE in some classes

- src/main/java/hudson/plugins/sshslaves/RemoteLauncher.java
Reverts jenkinsci/ssh-slaves-plugin#168
> Revert "[JENKINS-47510] RemoteLauncher.isUnix() is not overridden - always returns master OS"

- CHANGELOG.md
- doc/CONFIGURE.md
- src/main/java/hudson/plugins/sshslaves/PluginImpl.java
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
- src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
- src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
- src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java
See [JENKINS-42840](https://issues.jenkins-ci.org/browse/JENKINS-42840). There were some leftovers after https://github.com/jenkinsci/ssh-slaves-plugin/pull/96
This PR cleans up documentation and Javadoc + some tests while I was around
> [JENKINS-42840] - Cleanup the "slave" mention leftovers in the documentation

- pom.xml
JCasc had to create a new dependency that wasn't a `tests` classifier because maven doesn't allow you to bring dependencies through classifiers.
Upgrading here so that PCT works again,
Tracking:
https://github.com/jenkinsci/bom/pull/164
> Bump jcasc version

- README.md
- doc/CYGWIN.md
See [JENKINS-60827](https://issues.jenkins-ci.org/browse/JENKINS-60827).
This change moves https://wiki.jenkins.io/display/JENKINS/SSH+slaves+and+Cygwin and relevant comments there to the plugin documentation. All terminology is cleaned up there.
> [JENKINS-60827] - Move the Cygwin Wiki pages to GitHub, update the terminology

- pom.xml
Backports the following commits to 1.30.x:
- Bump jcasc version  (#173)
> [1.30.x] Bump jcasc version (#173)

- Jenkinsfile
I noticed that #178 was not publishing binaries due to https://github.com/jenkins-infra/pipeline-library/blob/c7acbe5bf68da0f1ad00d63d40a38e9dc59d6e6d/vars/buildPlugin.groovy#L58. While I am here, cleaning up a bit and aligning with https://github.com/jenkins-infra/pipeline-library/pull/120.
> Improved buildConfiguration

- src/main/java/hudson/plugins/sshslaves/JavaVersionChecker.java
This can happen on Windows most often with the existing installers (AdoptOpenJDK, Oracle JDK, etc).
I don't think this needs tests, but would be happy to look into it if maintainers think otherwise.
> Fix issue with Java installed into a path with spaces

- pom.xml
Change to use BOM introduces in the latest `org.jenkins-ci.plugins:plugi:4.x`
> chore: use BOM to manage the Jenkins Core dependencies

- src/main/java/hudson/plugins/sshslaves/JavaVersionChecker.java
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
See [JENKINS-65155](https://issues.jenkins-ci.org/browse/JENKINS-65155).
> [JENKINS-65155] The "java is not in the path" warning is show even though java is in the path

- src/main/java/hudson/plugins/sshslaves/JavaVersionChecker.java
This PR improves the error message to cover SSH agents running Java 11.
In my case, this error message was caused by this issue: https://github.com/jenkinsci/docker-ssh-agent/issues/33
I have not tested this PR.
Thanks!
> improve error message for Java missing on agent

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
This plugin consumes both Apache Commons IO and Guava, which seems redundant. One of the two can be dropped, so in this PR I'm dropping the dependency on Guava. Having fewer dependencies makes maintaining this plugin easier, and not depending on Guava means this plugin doesn't have to worry about any risk if/when Guava is upgraded in Jenkins core.
> Replace usages of `com.google.common.io.ByteStreams` with usages of `org.apache.commons.io.IOUtils`

- src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java
https://github.com/jenkinsci/ssh-slaves-plugin/pull/238 bumped sshd to 3.0.4. This moved mina-sshd from 1.7.0 to 2.5.1.
`CommandFactory` was moved to  a new package and is now causing `TrustHostKeyActionTest.testSubmitNotAuthorised` to fail. See https://github.com/jenkinsci/ssh-slaves-plugin/runs/3050443858
Need this also to resolve the same PCT failure.
cc @kuisathaverat
> update package name for CommandFactory for mina-sshd 2.5.1

- src/test/java/hudson/plugins/sshslaves/agents/AgentConnectionBase.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentUserAndPasswordConnectionTest.java
Fix the AgentUserAndPasswordConnectionTest test to use user and password.
> fix: use user and password instead of DSA key in the test

- pom.xml
Bump Jenkins core to nearest LTS
> chore: bump Jenkins core to 1.289.1 LTS version

- doc/CONFIGURE.md
Add ED-25519 and ECDSA as allowed host key algorithms.
Remove DSS because the DSA algorithm has been removed from OpenSSH. See https://security.stackexchange.com/questions/112802/why-openssh-deprecated-dsa-keys for the description of the removal of DSA/DSS.
Documentation change only.  No automated tests.
I've confirmed from my use of the current release of the plugin that ED-25519 and ECDSA public keys are allowed as the host key.
I've confirmed that the ssh-dss public host keys from my FreeNAS 12.1 host and from my OpenBSD 6.9 host are rejected by the current release of the plugin when running from the `jenkins/jenkins:2.303.1` Docker image.  The dialog box accepts the host key but the agent connection fails and the log reports that the host key is not recognized.   Recent Linux hosts …
> [JENKINS-66601] host key allows ed25519 & ecdsa

- README.md
The README specifies plugin rename was done in 1.32 but links to ssh-slaves-1.31.0 tag.
> Updated Readme ## Notes linkname to 1.31 instead of 1.32

- src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
Since Jenkins 2.267, there are 2 different category of monitors: security and non security ones.
In this plugin, the administrative monitor is enabled when an agent is connected using SSH keys but no key validation strategy is enabled is the connection configuration.
As this could lead to issues with those agent, it would be preferable that this monitor to be considered as a security one.
> Changes monitor category

- pom.xml
It changes the version number format to a one more accurate `1.999999.vabcdef456789`
related to https://github.com/jenkins-infra/jenkins.io/pull/4933
> chore: change the version number format

- src/test/java/hudson/plugins/sshslaves/agents/AgentDSAConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentECDHSha2Nistp256ConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentECDHSha2Nistp384ConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentRSA256ConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentRSA_AES128CBC_ConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentRSA_AES192CBC_ConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentRSA_DESCBC_ConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentRSA_DES_EDE3CBC_ConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentUbuntu1404RSAConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentUbuntu1604RSAConnectionTest.java
- src/test/java/hudson/plugins/sshslaves/agents/AgentUbuntu1804RSAConnectionTest.java
Test most common SSH connections, this PR disabled some of the old key formats and test the most common, we will continue having the tests for manual testing. This will reduce the time of the builds.
> chore: test most common SSH connections

- doc/CONFIGURE.md
This updates the description of the prefix/suffix commands for connecting to agents over SSH when Powershell is the default shell on the remote system.
See [JENKINS-67735](https://issues.jenkins.io/browse/JENKINS-67735).
Doc change only, so no tests needed.
> Update information for Windows OpenSSH agents

- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
Deadlock happens between:
(a) [synchronized void tearDownConnection](https://github.com/jenkinsci/ssh-slaves-plugin/blob/main/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L953)
(b) [synchronized (this) {](https://github.com/jenkinsci/ssh-slaves-plugin/blob/main/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L413)
Launch() is stuck here: [results = srv.invokeAll(callables);](https://github.com/jenkinsci/ssh-slaves-plugin/blob/main/src/main/java/hudson/plugins/sshslaves/SSHLauncher.java#L486) ,
and `callable` is stuck waiting here: [lock.wait(); // wait until the writer gives us something](https://github.com/jenkinsci/trilead-ssh2/blob/8e7118e74deacd7ef044df9076fcb9b95280c163/src/com/trilead/ssh2/channel/FifoBuffer.java#L212)
After some time `afterDisconnect` is called …
> Fix deadlock when afterDisconnect is called during launch()

- .gitignore
- Jenkinsfile
- pom.xml
- src/main/resources/hudson/plugins/sshslaves/SSHConnector/config.jelly
- src/main/resources/hudson/plugins/sshslaves/verifiers/KnownHostsFileKeyVerificationStrategy/config.jelly
- src/main/resources/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy/config.jelly
- src/main/resources/hudson/plugins/sshslaves/verifiers/ManuallyTrustedKeyVerificationStrategy/config.jelly
- src/main/resources/hudson/plugins/sshslaves/verifiers/NonVerifyingKeyVerificationStrategy/config.jelly
See [JENKINS-68195](https://issues.jenkins-ci.org/browse/JENKINS-68195).
After some improvements in the `f:dropdownDescriptorSelector` and the UI present in Jenkins Core 2.242 I need to change a couple of things in some jelly files. I have removed a workaround to show the help link on `f:dropdownDescriptorSelector` and I have to put the `f:dropdownDescriptorSelector` inside an `<f:entry>` to avoid showing the help button in the end of the right side of the browser. This is the visual result of the changes:
Before:
After:
Related to https://github.com/jenkinsci/jenkins/pull/5417
This PR cannot be merged before Jenkins Core 2.42 (or upper version) is released as LTS because it breaks the help links in previous versions.
> [JENKINS-68195] Duplicated help icon for Host Key verification

- src/main/resources/hudson/plugins/sshslaves/verifiers/TrustHostKeyAction/trustHostKey.jelly
> add some margin to the buttons on trustHostKey

- pom.xml
- src/main/java/hudson/plugins/sshslaves/SSHConnector.java
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).
> jep-227 downstream usage

- src/test/java/hudson/plugins/sshslaves/agents/AgentConnectionBase.java
Otherwise Windows agents waste time starting Jenkins _before_ skipping the test.
> Use `@ClassRule` for checking platform details

- Jenkinsfile
All of the Docker-based tests were being skipped in CI since (at least) #402.
> Enable Docker-based tests

- .github/CODEOWNERS
- CHANGELOG.md
- README.md
- doc/TROUBLESHOOTING.md
- pom.xml
The change proposed replaces up outdated terminology with the updated terminology. Once the PR has been accepted, I'll take care of the rename in other places, given GH handles redirects itself, everything will still work as before.
> Replace outdated terminology

- src/main/java/hudson/plugins/sshslaves/SSHConnector.java
- src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
https://github.com/jenkinsci/plugin-pom/pull/869 or a subsequent pull request that updates to 4.8.3 will need this change in the plugin to resolve new spotbugs warnings that will be reported by spotbugs 4.8.2 and later.
Plugin pom 4.77 is likely to include that new version of spotbugs.
Confirmed that the spotbugs warnings are visible when using the 4.77-SNAPSHOT plugin pom before this change. With this change, the spotbugs warnings are no longer visible.
```[tasklist]
```
> Suppress warnings for spotbugs 4.8.3

- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-curve25519-sha256/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-dsa/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ec/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ecdh-sha2-nistp256/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ecdh-sha2-nistp384/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ecdh-sha2-nistp521/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ed25519/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-host-ec/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-host-ed/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-host-rsa/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-rsa/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-rsa256/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-rsa512/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ubuntu-14.04/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ubuntu-16.04/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ubuntu-18.04/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ubuntu-20.04/Dockerfile
When running with Java 17 and a Jenkins Core built with `-Dmaven.compiler.target=17` tests are failing. This resolves the problem.
As Jenkins will be compiled with such option in just 20days, this is providing from prevention.
As you can see from this pull request build result, there is no problem with the current core requirement and those changes.
> Updates Java 11 to Java 17 for test environment

- .github/workflows/ssh-agent-docker.yml
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-base/Dockerfile
This new workflow will build an SSH Agent Docker image we can use to speed up the testcontainers tests.
> feat: new workflow to build a SSH Agent Base Docker image

- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-curve25519-sha256/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-dsa/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ec/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ecdh-sha2-nistp256/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ecdh-sha2-nistp384/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ecdh-sha2-nistp521/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ed25519/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-host-ec/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-host-ed/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-host-rsa/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-rsa/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-rsa256/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-rsa512/Dockerfile
- src/test/resources/hudson/plugins/sshslaves/agents/ssh-agent-ubuntu-20/Dockerfile
Change to use a prebuilt Docker image to run the TestContainers tests. It will speed up the tests, and improve the reliability
> feat: user prebuild base Docker image

- pom.xml
We bump the core ot support the two latest major versions from https://www.jenkins.io/changelog-stable/#v2.504.1 to [2.516.1](https://www.jenkins.io/changelog/2.516.1/).
This pull request updates the Jenkins baseline and version properties in the `pom.xml` file to align with a newer Jenkins version.
* **Jenkins version update**:
* Updated the `jenkins.baseline` property from `2.479` to `2.504`.
* Updated the `jenkins.version` property from `${jenkins.baseline}.3` to `${jenkins.baseline}.1`.
> chore: bump Jenkins Core
