pom.xml
src/main/java/hudson/plugins/sshslaves/SFTPClient.java
src/main/java/hudson/plugins/sshslaves/SSHConnector.java
src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

Enable FindBugs XML reports in the plugin

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

- without a timeout this can be left in the hands of trilead's infinite blocking on the socket
@reviewbybees

[FIXED JENKINS-23560] Time-out the afterDisconnect cleanup of the remote slave.jar

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

[JENKINS-40092](https://issues.jenkins-ci.org/browse/JENKINS-40092)
Completes 3c2d85607464330c9fb87c252f8eb9e63b6dc7ef to avoid breaking after https://github.com/jenkinsci/jenkins/pull/2633.
Also displays the SFTP error encountered when falling back to SCP.
@reviewbybees

[JENKINS-40092] Make copySlaveJarUsingSCP call right API for slave.jar

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

There are 2 changes here:
- More failure causes is considered recoverable.
- In case the exception is considered nonrecoverable, it is thrown instead of ignored.
https://issues.jenkins-ci.org/browse/JENKINS-41163
https://issues.jenkins-ci.org/browse/JENKINS-26379

Do not swallow IOException in case it is not recoverable

---

src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyTrustedKeyVerificationStrategy.java
src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java

[JENKINS-42969](https://issues.jenkins-ci.org/browse/JENKINS-42969)
Subsumes #49.
@reviewbybees & @mc1arke

[JENKINS-42969] Fix ManuallyTrustedKeyVerificationStrategy on 2.30+

---

src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java

Slaves are now called agents
@reviewbybees @jglick @stephenc @mc1arke

[JENKINS-42968] Fix PCT for 2.32.3

---

LICENSE.txt

Added a LICENSE.txt. The text of the license is the MIT license as written in the comment headers of the Java source files for this
project.

Added a LICENSE.txt to address Issue #60

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

https://issues.jenkins-ci.org/browse/JENKINS-48538
@reviewbybees

[FIXED JENKINS-48538] - Prevent NPE in SSHLauncher#isRecoverable()

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/ssh-slaves-plugin/32)

Replace shell with java instead of launching a new process

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

Reverts jenkinsci/ssh-slaves-plugin#32 to fix https://issues.jenkins-ci.org/browse/JENKINS-49032
@reviewbybees @jglick

Revert "Replace shell with java instead of launching a new process"

---

pom.xml

Add me to the developer list

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
src/main/resources/hudson/plugins/sshslaves/SSHConnector/config.jelly
src/main/resources/hudson/plugins/sshslaves/SSHConnector/help-disableTcpNoDelay.html
src/main/resources/hudson/plugins/sshslaves/SSHConnector/help-tcpNoDelay.html

[JENKINS-52660](https://issues.jenkins-ci.org/browse/JENKINS-52660)
* Configuration option to enable/disable TCP_NODELAY

[JENKINS-52660] Allow to disable TCP_NODELAY

---

pom.xml

add a warning about incompatible changes

compatibleSinceVersion

---

CHANGELOG.md
Jenkinsfile
pom.xml

* [JENKINS-54884](https://issues.jenkins-ci.org/browse/JENKINS-54884) 
* [JENKINS-54746](https://issues.jenkins-ci.org/browse/JENKINS-54746)
Use Trilead ssh2 from Jenkins Core and use Trilead API plugin for test

[JENKINS-54884][JENKINS-54746] use Trilead API plugin only for test

---

CHANGELOG.md
Jenkinsfile
src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
src/main/resources/hudson/plugins/sshslaves/Messages.properties
src/main/resources/hudson/plugins/sshslaves/SSHConnector/help-host.html

[JENKINS-56885](https://issues.jenkins-ci.org/browse/JENKINS-56885)
* update Jenkinsfile to test the latest weekly 
* Do not allow null hosts
* Check configuration before to launch the agent 
* Help for the Hosts configuration field
* validate the Hosts configuration field

[JENKINS-56885] It is possible to save a Node without host configuration

---

pom.xml

https://github.com/jenkinsci/ssh-credentials-plugin/releases

udpate ssh-credentials from 1.14 to 1.16

---

CHANGELOG.md

spelling and grammar

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

see [JENKINS-58588](https://issues.jenkins-ci.org/browse/JENKINS-58588)

[JENKINS-58588] do not remove remoting.jar on disconnection

---

pom.xml
src/test/java/hudson/plugins/sshslaves/SSHLauncherCasCRoundTripTest.java

https://github.com/jenkinsci/configuration-as-code-plugin/pull/1049

fix space in expected log

---

src/main/resources/hudson/plugins/sshslaves/SSHConnector/config_zh_TW.properties
src/main/resources/hudson/plugins/sshslaves/SSHLauncher/help.properties
src/main/resources/hudson/plugins/sshslaves/SSHLauncher/help_de.properties
src/main/resources/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor/message.jelly
src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java

See [JENKINS-42840](https://issues.jenkins-ci.org/browse/JENKINS-42840).
There has still been some occurrences of "slave" in user facing messages.

[JENKINS-42840] Slave to agent renaming (leftovers)

---

.editorconfig

add .editorconfig configuration file

chore: add .editorconfig configuration file

---

doc/CONFIGURE.md
src/main/java/hudson/plugins/sshslaves/verifiers/KnownHostsFileKeyVerificationStrategy.java
src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java

See [JENKINS-45001](https://issues.jenkins-ci.org/browse/JENKINS-45001).

[JENKINS-45001] KnownHostsFileKeyVerificationStrategy is not configuable

---

README.md
doc/TROUBLESHOOTING.md
pom.xml

See [JENKINS-59427](https://issues.jenkins-ci.org/browse/JENKINS-59427). I did not touch artifact ID and the related fields for now

[JENKINS-59427] - Rename the plugin to SSH Build Agents Plugin

---

src/main/java/hudson/plugins/sshslaves/RemoteLauncher.java

See [JENKINS-47510](https://issues.jenkins-ci.org/browse/JENKINS-47510).
@jtnord

[JENKINS-47510] RemoteLauncher.isUnix() is not overridden - always returns master OS

---

README.md

See [JENKINS-XXXXX](https://issues.jenkins-ci.org/browse/JENKINS-XXXXX).

Update the changelog badge title to make the purpose more explicit

---

src/main/java/hudson/plugins/sshslaves/verifiers/KnownHostsFileKeyVerificationStrategy.java
src/main/resources/hudson/plugins/sshslaves/Messages.properties

See [JENKINS-60812](https://issues.jenkins-ci.org/browse/JENKINS-60812).
test environment https://github.com/kuisathaverat/jenkins-issues/tree/master/JENKINS-60812

[JENKINS-60812] Failed known_hosts verification for non-standard ssh port

---

doc/CONFIGURE.md

See [JENKINS-61356](https://issues.jenkins-ci.org/browse/JENKINS-61356).
Adds a note about the supported key formats.

docs: note about supported key formats

---

doc/TROUBLESHOOTING.md

See [JENKINS-61356](https://issues.jenkins-ci.org/browse/JENKINS-61356).
Adds a note about the supported key formats.

docs: add also a troubleshooting section

---

doc/CYGWIN.md

Fix typo in CYGWIN.md

---

src/main/java/hudson/plugins/sshslaves/SSHConnector.java
src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
src/main/resources/hudson/plugins/sshslaves/SSHConnector/config.jelly
src/main/resources/hudson/plugins/sshslaves/SSHLauncher/config.jelly

See [JENKINS-58691](https://issues.jenkins-ci.org/browse/JENKINS-58691).
- ~[ ] Appropriate autotests or explanation to why this change has no tests~

[JENKINS-58691] require POST and permissions to doXXXXX methods

---

doc/TROUBLESHOOTING.md

It adds documentation about how to enable keepalive traffic on SSH services.

docs: add keepalive documentation

---

src/main/java/hudson/plugins/sshslaves/DefaultJavaProvider.java
src/main/java/hudson/plugins/sshslaves/JavaVersionChecker.java
src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java

See [JENKINS-64404](https://issues.jenkins-ci.org/browse/JENKINS-64404).
- ~[ ] Appropriate autotests or explanation to why this change has no tests~

[JENKINS-64404] quote java path when it has whitespaces

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
src/main/resources/hudson/plugins/sshslaves/Messages.properties
src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java

See [JENKINS-64404](https://issues.jenkins-ci.org/browse/JENKINS-64404).

[JENKINS-64404] add a whitespaces check on the javaPath setting

---

src/main/java/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor.java
src/main/resources/hudson/plugins/sshslaves/verifiers/MissingVerificationStrategyAdministrativeMonitor/message.jelly

See [JENKINS-60289](https://issues.jenkins-ci.org/browse/JENKINS-60289).
- ~[ ] Appropriate autotests or explanation to why this change has no tests~

[JENKINS-60289] SSH Host Key Verifiers not configured

---

src/main/java/hudson/plugins/sshslaves/DefaultJavaProvider.java
src/main/java/hudson/plugins/sshslaves/JavaVersionChecker.java
src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

See [JENKINS-64420](https://issues.jenkins-ci.org/browse/JENKINS-64420).
- ~[ ] Appropriate autotests or explanation to why this change has no tests~

Deprecated javaVersionChecker

---

pom.xml

See https://github.com/jenkinsci/bom/pull/449 and https://github.com/jenkinsci/jenkins/pull/5049
Tests fail on 2.282 without this change
We will need a release for bom please
cc @kuisathaverat

Update baseline to 2.282, fixes PCT (detached ssh plugin)

---

src/test/java/hudson/plugins/sshslaves/rules/CheckIsDockerAvailable.java

See [JENKINS-65929](https://issues.jenkins-ci.org/browse/JENKINS-65929).
- [C] Appropriate autotests or explanation to why this change has no tests

[JENKINS-65929] Detection of docker is unreliable

---

src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyTrustedKeyVerificationStrategy.java

See [JENKINS-42969](https://issues.jenkins.io/browse/JENKINS-42969) / #50.
I came across the todo; JENKINS-42969 has been fixed in core 2.46 already.

[JENKINS-42969] Use Computer.addAction()

---

src/main/java/hudson/plugins/sshslaves/JavaProvider.java
src/main/java/hudson/plugins/sshslaves/JavaVersionChecker.java
src/main/java/hudson/plugins/sshslaves/SSHConnector.java
src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
src/main/java/hudson/plugins/sshslaves/verifiers/KnownHostsFileKeyVerificationStrategy.java
src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyTrustedKeyVerificationStrategy.java
src/main/java/hudson/plugins/sshslaves/verifiers/NonVerifyingKeyVerificationStrategy.java
src/test/java/hudson/plugins/sshslaves/rules/CheckIsDockerAvailable.java

See [JENKINS-55973](https://issues.jenkins.io/browse/JENKINS-55973) / https://github.com/jenkinsci/jenkins/pull/4604.
No tests needed; only annotations changed / added.

Missing nullability annotations added and JSR 305 replaced

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
src/test/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyActionTest.java

Modernizes some assertions and replaces anonymous classes with lambdas.
I'd appreciate someone having more insight having a look at the later, just to make sure it doesn't break compatibility.

Replace assertion and use lambda

---

.github/dependabot.yml
.github/release-drafter.yml
.github/workflows/cd.yaml
.mvn/maven.config
pom.xml

This comes with a new version number format, see https://www.jenkins.io/jep/229

feat: enable continuous delivery

---

pom.xml
src/test/java/hudson/plugins/sshslaves/agents/AgentUbuntu2004RSAConnectionTest.java

chore: update Jenkins Core to 2.319

---

src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java

supersede https://github.com/jenkinsci/ssh-slaves-plugin/pull/322

fix: change the test connection parameters to fail faster

---

pom.xml

Since this PR the compatibility with Java 8 is not guaranteed and is not supported.
* feat: bump Jenkins core to 2.361

feat: Remove support for Java 8

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java
src/main/java/hudson/plugins/sshslaves/verifiers/ManuallyProvidedKeyVerificationStrategy.java
src/main/java/hudson/plugins/sshslaves/verifiers/TrustHostKeyAction.java

fix: Stapler: Missing permission check

fix: Stapler: Missing permission check

---

pom.xml

fix: Update pom.xml to 2.361.1

---

src/main/java/hudson/plugins/sshslaves/SSHLauncher.java

Remove dead code

---

pom.xml

Bump BOM, baseline

---

pom.xml

Bump jenkins core to 2.462 latest version supporting Java 11

---

pom.xml

chore: bump Jenkins Core
Require Java 17
https://www.jenkins.io/changelog-stable/2.479.1/

chore: bump Jenkins Core

---

pom.xml

Signed-off-by: Olivier Lamy <olamy@apache.org>

Remove not anymore needed exclusions which breaks PCT test from 2.489, test with mvn clean install -Djenkins.version=2.489

---

src/test/java/hudson/plugins/sshslaves/SSHLauncherTest.java
src/test/resources/hudson/plugins/sshslaves/openjdk-6-linux.version
src/test/resources/hudson/plugins/sshslaves/openjdk-7-netbsd.version
src/test/resources/hudson/plugins/sshslaves/oracle-java-1.7-mac.version
src/test/resources/hudson/plugins/sshslaves/oracle-java-1.8-mac.version
src/test/resources/hudson/plugins/sshslaves/sun-java-1.4-linux.version
src/test/resources/hudson/plugins/sshslaves/sun-java-1.6-linux.version
src/test/resources/hudson/plugins/sshslaves/sun-java-1.6-mac.version

fix: remove obsolete test
these test check for Obsolete and unsupported Java versions

fix: remove obsolete test

---

doc/CONFIGURE.md

Typo "the the"

---

pom.xml

Use `credentials` version from plugin BOM
